# Usa la imagen base de Python
FROM python:3.11

# Establece el directorio de trabajo
WORKDIR /app

# Copia el archivo de dependencias
COPY ./requirements.txt /app/requirements.txt

# Instala las dependencias del sistema
RUN apt-get update && apt-get install -y python3-distutils git && apt-get clean && rm -rf /var/lib/apt/lists/*

# Instala las dependencias de Python
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copia el resto de los archivos del proyecto
COPY . /app

# Expone el puerto 8000 para la aplicación Django
EXPOSE 8000

# Comando para ejecutar la aplicación
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
